    # Time Map

    TimeMap.create(time_offset:17 ,time_zone:-5)
    TimeMap.create(time_offset:16 ,time_zone:-4)
    TimeMap.create(time_offset:15 ,time_zone:-3)
    TimeMap.create(time_offset:14 ,time_zone:-2)
    TimeMap.create(time_offset:13 ,time_zone:-1)
    TimeMap.create(time_offset:12 ,time_zone:0)
    TimeMap.create(time_offset:11 ,time_zone:1)
    TimeMap.create(time_offset:10 ,time_zone:2)
    TimeMap.create(time_offset:9 ,time_zone:3)
    TimeMap.create(time_offset:8 ,time_zone:4)
    TimeMap.create(time_offset:7 ,time_zone:5)
    TimeMap.create(time_offset:6 ,time_zone:6)
    TimeMap.create(time_offset:5 ,time_zone:7)
    TimeMap.create(time_offset:4 ,time_zone:8)
    TimeMap.create(time_offset:3 ,time_zone:9)
    TimeMap.create(time_offset:2 ,time_zone:10)
    TimeMap.create(time_offset:1 ,time_zone:11)
    TimeMap.create(time_offset:0 ,time_zone:12)
    TimeMap.create(time_offset:23 ,time_zone:-11)
    TimeMap.create(time_offset:22 ,time_zone:-10)
    TimeMap.create(time_offset:21 ,time_zone:-9)
    TimeMap.create(time_offset:20 ,time_zone:-8)
    TimeMap.create(time_offset:19 ,time_zone:-7)
    TimeMap.create(time_offset:18 ,time_zone:-6)


    # first iteration
    Location.create(time_zone:-5,place:"Boston, Massachusettts",drink:"a Sam Adams",href:"http://www.samueladams.com/")
  	Location.create(time_zone:-4,place:"Santo Domingo, Dominican Republic",drink:"a Cerveza Soberana",href:"http://www.barupanama.com/php/detallemarcas.php?idproducto=406") 
  	Location.create(time_zone:-3,place:"Santiago, Chile",drink:"a Cerveza Grassau",href:"http://www.cervezagrassau.cl/") 
  	Location.create(time_zone:-2,place:"Rio de Janiero, Brazil",drink:"a Perigosa Imperial IPA",href:"http://beeradvocate.com/beer/profile/25832/72112") 
  	Location.create(time_zone:-1,place:"Azores, Portugal",drink:"a Sagres Bohemia",href:"http://www.ratebeer.com/beer/sagres-bohemia/47579/") 
  	Location.create(time_zone:0,place:"Dublin, Ireland",drink:"a Guinness",href:"http://www.guinness.com/en-us/") 
  	Location.create(time_zone:0,place:"London, England",drink:"a Warm Beer",href:"http://en.wikipedia.org/wiki/Beer_in_England#Temperature")
  	Location.create(time_zone:1,place:"Hamburg, Germany",drink:"a Schwarzbier",href:"http://beeradvocate.com/beer/style/31") 
  	Location.create(time_zone:1,place:"Amsterdam, Netherlands",drink:"a Heineken",href:"http://www.heineken.com/us/") 
  	Location.create(time_zone:1,place:"Brussels, Belgium",drink:"a Flemish Brown Ale",href:"http://www.bevx.com/beer/belgian/flembrown_home") 
  	Location.create(time_zone:2,place:"Cape Town, South Africa",drink:"a Castle Lager",href:"http://www.castlelager.co.za/") 
  	Location.create(time_zone:2,place:"Athens, Greece",drink:"a Zeos Pilsner",href:"http://www.ratebeer.com/beer/zeos-pilsner/101480/") 
  	Location.create(time_zone:2,place:"Istanbul, Turkey",drink:"an Efes Pilsen",href:"http://www.efespilsen.com.tr/") 
  	Location.create(time_zone:3,place:"Doha, Qatar",drink:"a Chimay Bleue Lager",href:"http://uncyclopedia.wikia.com/wiki/Chimay_Blue") 
  	Location.create(time_zone:4,place:"Moscow, Russia",drink:"some Vodka",href:"http://www.russianstandardvodka.com/") 
  	Location.create(time_zone:5,place:"Islamabad, Pakistan",drink:"a Murree Beer",href:"http://www.murreebrewery.com/pord.html") 
  	Location.create(time_zone:6,place:"Almaty, Kazakhstan",drink:"a Tian Shan Krepkoye Ale",href:"http://beeradvocate.com/beer/profile/13627/30012/?ba=Globetrotter") 
  	Location.create(time_zone:7,place:"Hanoi, Vietnam",drink:"some Snake Wine",href:"http://en.wikipedia.org/wiki/Snake_wine") 
  	Location.create(time_zone:8,place:"Kuala Lumpur, Malaysia",drink:"a Tiger Beer",href:"http://www.tigerbeer.com/") 
  	Location.create(time_zone:8,place:"Shanghai, China",drink:"a Zhujiang Beer",href:"http://www.zhujiangbeer.ca/") 
  	Location.create(time_zone:9,place:"Seoul, South Korea",drink:"a Cass Lager",href:"https://untappd.com/b/oriental-brewery-inbev-cass-lager/11337") 
  	Location.create(time_zone:9,place:"Tokyo, Japan",drink:"an Asahi Gold Lager",href:"http://www.ratebeer.com/beer/asahi-gold-lager-beer/111684/") 
  	Location.create(time_zone:10,place:"Guam",drink:"a Great Deep Oatmeal Stout",href:"http://www.ratebeer.com/beer/great-deep-oatmeal-stout/38228/") 
  	Location.create(time_zone:11,place:"Melbourne, Australia",drink:"a Fosters",href:"http://www.fostersbeer.com/") 
  	Location.create(time_zone:12,place:"Anadyr, Russia",drink:"some Vodka",href:"http://www.russianstandardvodka.com/") 
  	Location.create(time_zone:-11,place:"Pago Pago, American Samoa",drink:"a Vailima Lager",href:"http://www.ratebeer.com/beer/vailima-special-export-lager/75157/")  
  	Location.create(time_zone:-10,place:"Honolulu, Hawaii",drink:"a Big Wave Golden Ale",href:"http://konabrewingco.com/blog/beers/big-wave-golden-ale/") 
  	Location.create(time_zone:-9,place:"Anchorage, Alaska",drink:"a Cold One",href:"https://www.coorslight.com/AgeGate/") 
  	Location.create(time_zone:-8,place:"Seattle, Washington",drink:"a Dark and Stormy",href:"http://cocktails.about.com/od/cocktailrecipes/r/dark_strmy_cktl.htm") 
  	Location.create(time_zone:-8,place:"Los Angeles, California",drink:"a Natural Ice",href:"http://www.naturallight.com/")
  	Location.create(time_zone:-7,place:"Phoenix, Arizona",drink:"a Bells Expedition Stout",href:"http://bellsbeer.com/") 
  	Location.create(time_zone:-6,place:"San Antonio, Texas",drink:"a Rahr and Sons Ugly Pug Black Lager",href:"http://rahrbrewing.com/all_beers/ugly-pug/") 


    # Second iteration
    # Location.create(time_zone:?,place:"???",drink:"#",href:"#")
    Location.create(time_zone:18,place:"Chicago, Illinois",drink:"a Gossamer Golden Ale",href:"http://halfacrebeer.com/gossamer-golden-ale")
    Location.create(time_zone:11,place:"Madrid, Spain",drink:"some Sangria",href:"http://wine.about.com/od/redwines/r/basicSangria.htm")
    Location.create(time_zone:17,place:"Philadelphia, Pennsylvania",drink:"a Yards Pale Ale",href:"http://www.yardsbrewing.com/signature-ales")
    Location.create(time_zone:0,place:"Casablanca, Morocco",drink:"a Flag Speciale",href:"http://www.ratebeer.com/beer/flag-speciale-morocco/13890/")
    Location.create(time_zone:-6,place:"Mexico City, Mexico",drink:"a Carta Blanca Cerveza",href:"http://www.cartablanca.com.mx/")
    Location.create(time_zone:-6,place:"New Orleans, Louisiana",drink:"a Sazerac",href:"http://cocktails.about.com/od/s/r/szrc_cktl.htm")
    Location.create(time_zone:1,place:"Paris, France",drink:"some Bourgogne Chardonnay",href:"http://www.snooth.com/region/france/burgundy/bourgogne-chardonnay/")
    Location.create(time_zone:1,place:"Vienna, Austria",drink:"some Schnapps",href:"http://dekuyperusa.com/flavor/dekuyper-pucker-peach-schnapps-liqueur")
    Location.create(time_zone:-5,place:"Ottawa, Ontario",drink:"some Canadian Rye Whisky",href:"http://www.1910ryewhisky.com/")
    Location.create(time_zone:1,place:"Prague, Czech Republic",drink:"some Slivovitz",href:"http://en.wikipedia.org/wiki/Slivovitz")
    Location.create(time_zone:3,place:"Baghdad, Iraq",drink:"some Arak",href:"http://en.wikipedia.org/wiki/Arak_(drink)")
    Location.create(time_zone:2,place:"Sofia, Bulgaria",drink:"a Pirinsko Pivo Ale",href:"http://www.pirinskopivo.bg/")
    Location.create(time_zone:-5,place:"Havana, Cuba",drink:"a Mojito",href:"http://allrecipes.com/recipe/the-real-mojito/")
    Location.create(time_zone:2,place:"Helsinki, Finland",drink:"some Finlandia Vodka",href:"http://www.finlandia.com/age.aspx")
    Location.create(time_zone:1,place:"Stockholm, Sweden",drink:"some Swedish Snaps",href:"http://sweden.se/culture/snaps-and-glogg/")
    Location.create(time_zone:8,place:"Taipei, Taiwan",drink:"some Kaoliang",href:"http://www.kkl.gov.tw/eng/taste_3_1.aspx")
    Location.create(time_zone:0,place:"Reykjavik, Iceland",drink:"some Brennivin (Black Death)",href:"http://www.nordicstore.net/icelandic_brennivin_521_prd1.htm")
    Location.create(time_zone:2,place:"Kyiv, Ukraine",drink:"some Horilka",href:"http://www.wumag.kiev.ua/index2.php?param=pgs20052/156")
    Location.create(time_zone:12,place:"Lautoka, Fiji",drink:"some Bounty Rum",href:"http://www.fijirumco.com/fiji-rum-story/bounty-rum")
    #Location.create(time_zone:?,place:"???",drink:"#",href:"#")




