class TimeMapPopulate < ActiveRecord::Migration
  def change
  	TimeMap.create(time_offset:17 ,time_zone:"UTC-5")
  	TimeMap.create(time_offset:16 ,time_zone:"UTC-4")
  	TimeMap.create(time_offset:15 ,time_zone:"UTC-3")
  	TimeMap.create(time_offset:14 ,time_zone:"UTC-2")
  	TimeMap.create(time_offset:13 ,time_zone:"UTC-1")
  	TimeMap.create(time_offset:12 ,time_zone:"UTC0")
  	TimeMap.create(time_offset:11 ,time_zone:"UTC+1")
  	TimeMap.create(time_offset:10 ,time_zone:"UTC+2")
  	TimeMap.create(time_offset:9 ,time_zone:"UTC+3")
  	TimeMap.create(time_offset:8 ,time_zone:"UTC+4")
  	TimeMap.create(time_offset:7 ,time_zone:"UTC+5")
  	TimeMap.create(time_offset:6 ,time_zone:"UTC+6")
  	TimeMap.create(time_offset:5 ,time_zone:"UTC+7")
  	TimeMap.create(time_offset:4 ,time_zone:"UTC+8")
  	TimeMap.create(time_offset:3 ,time_zone:"UTC+9")
  	TimeMap.create(time_offset:2 ,time_zone:"UTC+10")
  	TimeMap.create(time_offset:1 ,time_zone:"UTC+11")
  	TimeMap.create(time_offset:24 ,time_zone:"UTC+12")
  	TimeMap.create(time_offset:23 ,time_zone:"UTC-11")
  	TimeMap.create(time_offset:22 ,time_zone:"UTC-10")
  	TimeMap.create(time_offset:21 ,time_zone:"UTC-9")
  	TimeMap.create(time_offset:20 ,time_zone:"UTC-8")
  	TimeMap.create(time_offset:19 ,time_zone:"UTC-7")
  	TimeMap.create(time_offset:18 ,time_zone:"UTC-6")
  end
end
