class InitialPopulate < ActiveRecord::Migration
  def change
  	Location.create(time_offset:17,place:"Boston, Massachusettts",drink:"a Sam Adams")
  	Location.create(time_offset:16,place:"Santo Domingo, Dominican Republic",drink:"a Cerveza Soberana") 
  	Location.create(time_offset:15,place:"Santiago, Chile",drink:"a Cerveza Grassau") 
  	Location.create(time_offset:14,place:"Rio de Janiero, Brazil",drink:"a Perigosa Imperial IPA") 
  	Location.create(time_offset:13,place:"Azores, Portugal",drink:"a Sagres Bohemia") 
  	Location.create(time_offset:12,place:"Dublin, Ireland",drink:"a Guinness") 
  	Location.create(time_offset:12,place:"London, England",drink:"a Warm Beer")
  	Location.create(time_offset:11,place:"Hamburg, Germany",drink:"a Schwarzbier") 
  	Location.create(time_offset:11,place:"Amsterdam, Netherlands",drink:"a Heineken") 
  	Location.create(time_offset:11,place:"Brussels, Belgium",drink:"a Flemish Brown Ale") 
  	Location.create(time_offset:10,place:"Cape Town, South Africa",drink:"a Castle Lager") 
  	Location.create(time_offset:10,place:"Athens, Greece",drink:"a Zeos Pilsner") 
  	Location.create(time_offset:10,place:"Istanbul, Turkey",drink:"an Efes Pilsen") 
  	Location.create(time_offset:9,place:"Doha, Qatar",drink:"a Chimay Bleue Lager") 
  	Location.create(time_offset:8,place:"Moscow, Russia",drink:"some Vodka") 
  	Location.create(time_offset:7,place:"Islamabad, Pakistan",drink:"a Murree Beer") 
  	Location.create(time_offset:6,place:"Almaty, Kazakhstan",drink:"a Tian Shan Krepkoye Ale") 
  	Location.create(time_offset:5,place:"Hanoi, Vietnam",drink:"a Passion Fruit Witbier Draft") 
  	Location.create(time_offset:4,place:"Kuala Lumpur, Malaysia",drink:"a Tiger Beer") 
  	Location.create(time_offset:4,place:"Shanghai, China",drink:"a Zhujiang Beer") 
  	Location.create(time_offset:3,place:"Seoul, South Korea",drink:"a Cass Lager") 
  	Location.create(time_offset:3,place:"Tokyo, Japan",drink:"an Asahi Gold Lager") 
  	Location.create(time_offset:2,place:"Guam",drink:"a Great Deep Oatmeal Stout") 
  	Location.create(time_offset:1,place:"Melbourne, Australia",drink:"a Fosters") 
  	Location.create(time_offset:24,place:"Anadyr, Russia",drink:"some Vodka") 
  	Location.create(time_offset:23,place:"Pago Pago, American Samoa",drink:"a Vailima Lager")  
  	Location.create(time_offset:22,place:"Honolulu, Hawaii",drink:"a Big Wave Golden Ale") 
  	Location.create(time_offset:21,place:"Anchorage, Alaska",drink:"a Cold One") 
  	Location.create(time_offset:20,place:"Seattle, Washington",drink:"a Dark and Stormy") 
  	Location.create(time_offset:20,place:"Los Angeles, California",drink:"a Natural Ice")
  	Location.create(time_offset:19,place:"Phoenix, Arizona",drink:"a Bells Expedition Stout") 
  	Location.create(time_offset:18,place:"San Antonio, Texas",drink:"a Rahr and Sons Ugly Pug Black Lager") 


  end
end
